class PctbSubjectLists {
  List<String> list_9th = [
    'Urdu',
    'English',
    'Islamic Studies',
    'Pakistan Studies',
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Genral Mathematics',
    'Mathematics(UM ',
    'Physics(UM ',
    'Chemistry(UM ',
    'Biology(UM ',
    'Genral Mathematics(UM ',
    'TARJUMA-TUL-QURAN',
    'Computer Science',
    'Computer Science(UM ',
    'Computer Science(P ',
    'Akhlaqiat 9-10(optional ',
    'Farsi 9-10',
    'General Science(EM 9-10',
    'General Science(UM 9-10',
  ];
  List<String> list_10th = [
    'English',
    'Urdu',
    'Islamic Studies',
    'Pakistan Studies',
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Genral Mathematics',
    'Mathematics(UM ',
    'Physics(UM ',
    'Chemistry(UM ',
    'Biology(UM ',
    'Genral Mathematics(UM ',
    'TARJUMA-TUL-QURAN',
    'Computer Science',
    'Computer Science(UM ',
    'Computer Science(P ',
    'Akhlaqiat 9-10(optional ',
    'Farsi 9-10',
    'General Science(EM 9-10',
    'General Science(UM 9-10',
  ];
  List<String> list_11th = [
    'Urdu',
    'English Book 1',
    'English Book 3',
    'Islamic Studies',
    'Physical Geography',
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Islamiyat(UM) ',
    'Statistics',
    'Economics',
    'Civics',
    'Punjabi Ikhtiari',
    'TARJUMA-TUL-QURAN',
    'Computer Science',
    'Ilm-ul-Taleem',
    'Hadiqat-ul-Adab0',
    'Psychology',
    'Farsi ',
    'Mubadiyat Falsfa',
    'Muraqa-e-Adab',
    "Akhlaqiat 11-12(optional)",
  ];
  List<String> list_12th = [
    'Urdu',
    'English Book 2',
    'Mr. Chips',
    'Pak Studies',
    'Human Geography',
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Pak Study(UM) ',
    'Statistics',
    'Economics',
    'Civics',
    'Punjabi Ikhtiari',
    'TARJUMA-TUL-QURAN',
    'Computer Science',
    'Ilm-ul-Taleem',
    'Hadiqat-ul-Adab0',
    'Psychology',
    'Farsi ',
    'Mantaq',
    "Akhlaqiat 11-12(optional)",
  ];
}
