// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYysIXwwK0U1_-uxX3BlA5OrJtvDfbd74',
    appId: '1:715056186027:web:72409f3e129cf654ebadee',
    messagingSenderId: '715056186027',
    projectId: 'teacher-assist-3afdc',
    authDomain: 'teacher-assist-3afdc.firebaseapp.com',
    storageBucket: 'teacher-assist-3afdc.appspot.com',
    measurementId: 'G-Y05GKF5LNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPgqNJB1oMXW4pzsGlhep_B8Ps1p0Uluo',
    appId: '1:715056186027:android:50b4618eec2bb89eebadee',
    messagingSenderId: '715056186027',
    projectId: 'teacher-assist-3afdc',
    storageBucket: 'teacher-assist-3afdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDttoNb9ivZ1NP3mYGEv7d7F3qpsG8LemY',
    appId: '1:715056186027:ios:ba12908a33254beaebadee',
    messagingSenderId: '715056186027',
    projectId: 'teacher-assist-3afdc',
    storageBucket: 'teacher-assist-3afdc.appspot.com',
    iosClientId: '715056186027-jd0dc846n22qlfo3jdlfi7843n9r5l8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.assistTeacher',
  );
}
